name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  test-ssm-connectivity:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Test SSM Connectivity
      id: test-ssm-connectivity
      uses: nohmad/aws-ssm-send-command-action@v1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        document-name: AWS-RunShellScript
        targets: '[{"Key":"InstanceIds","Values":["${{ secrets.EC2_INSTANCE_ID }}"]}]'
        parameters: '{"commands":["echo Hello World"]}'
        timeout: 30

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-ssm-connectivity
    steps:
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker Image to GHCR
      id: build-and-push-docker-image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/backend:latest .
        docker push ghcr.io/${{ github.repository }}/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy to EC2 via SSM
      uses: nohmad/aws-ssm-send-command-action@v1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        document-name: AWS-RunShellScript
        targets: '[{"Key":"InstanceIds","Values":["${{ secrets.EC2_INSTANCE_ID }}"]}]'
        parameters: >
          {"commands":["sudo su - ubuntu -c 'cd /home/ubuntu/topazio-shop-backend-aws && git pull origin main && npm install && pm2 restart all'"]}
        timeout: 60
